### ISSUE TITLE
Why is policy customization removed in 4.7?

### ISSUE THREAD

**Issue by adrianchifor** [openshift/cluster-kube-descheduler-operator#195]
In 4.6 we could configure the descheduler policies with the `strategies` field as the defaults don't work for us, but now in 4.7 the field is deprecated and can only enable the default profiles with no configuration options. Our only choices now are to keep using the 4.6 operator or remove it completely and run descheduler ourselves.

**Comment by damemi** [comment]
Hi @adrianchifor 
We made the decision to restrict configuration in the GA OpenShift release of the Descheduler Operator (4.7) for a number of reasons. The primary goal was to provide a minimal, stable set of predefined configurations for which we knew we could reliably provide support and development for production customer environments.

By abstracting the raw policy configuration away, there is also the benefit of simplifying setup for users and ensuring consistency across platform upgrades. For example if the upstream Policy API changes (as it is [very likely to do](https://github.com/kubernetes-sigs/descheduler/issues/486)), the profiles we have defined will continue to provide the same intent-based functionality without requiring any action from administrators to react to changes between underlying versions.

However part of this change has been an active search for feedback on where these settings could be improved and which options could also be exposed through the operator config. If you have a specific use case, please open a new issue or customer RFE where we can discuss it further. We already have a number of these requests which we are planning to implement in upcoming versions.

If you are interested, for more information on this design and some of the backstory on why we went this route please see our blog post on the Red Hat blog announcing the 4.7 Descheduler GA for OpenShift: https://www.openshift.com/blog/descheduler-ga-in-openshift-4.7

**Comment by adrianchifor** [comment]
Thanks for the background on the decision, nothing wrong with simplifying the setup and offering minimal defaults. However, this is not ideal for current users that have already configured the strategies to match their use-cases. For example in our case, we can't run the descheduler without the thresholdPriorityClass option as we don't want to disrupt specific workloads. The predefined, very arbitrary defaults (like 20%/50% for low node usage) do not work for the majority of cluster operators and stripping away the configuration options basically tells us to go away and run this ourselves.

**Comment by damemi** [comment]
Hi, I'm sorry for the disruption these changes have caused for you and your team. In [OpenShift 4.6 and earlier](https://docs.openshift.com/container-platform/4.6/nodes/scheduling/nodes-descheduler.html), this operator was in [Tech Preview](https://access.redhat.com/solutions/21101), which denotes that it is not recommended for production use and features may change or be removed. However, the graduation of the operator to GA ensures that from this point on the provided features are stable and will not significantly change without following the established deprecation procedures.

> stripping away the configuration options basically tells us to go away and run this ourselves.

This was not our intention, on the contrary we are actively soliciting user feedback exactly like this to provide criticism and requests for settings that were left out of the initial release. The two options you mentioned (low node usage and priorityClass thresholds) have been requested by other users and are already being reviewed to be added back in. Your +1 for those helps greatly.

If there are any other specific features or use cases you are missing, please open them as their own issues (or as an RFE through the Red Hat channels). We are listening to your feedback, and working to provide requests in a way that is both reliable and usable in production environments.

Thank you for taking the time to share your perspective as a user, it is very helpful to the improvement of the project!

**Comment by adrianchifor** [comment]
Yea completely understand the tech preview, we knew some tweaks were needed to the operator config when we upgraded to 4.7, but we definitely didn't expect full backwards incompatibility and zero configuration options. Also very surprised that this feedback wasn't gathered during the preview phase, but instead chose to go GA, wait for people to complain on whats missing and promise to add things back.

The whole point of the operator is to abstract the configuration and make the setup easy, so right now the GA version offers nothing more compared to the descheduler helm chart.

**Comment by adrianchifor** [comment]
Just to prove the point above, this is the helm release configuration we moved to, which is smaller and simpler than the descheduler operator config we had in 4.6

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: flux
spec:
  releaseName: descheduler
  targetNamespace: descheduler
  chart:
    name: descheduler
    repository: https://kubernetes-sigs.github.io/descheduler/
    version: 0.20.0
  values:
    schedule: "*/30 * * * *"

    startingDeadlineSeconds: 120
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 10

    deschedulerPolicy:
      strategies:
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 30
                memory: 30
                pods: 30
              targetThresholds:
                cpu: 70
                memory: 70
                pods: 70
              thresholdPriorityClassName: "high"

        RemoveDuplicates:
          enabled: false
        RemovePodsViolatingNodeTaints:
          enabled: false
        RemovePodsViolatingNodeAffinity:
          enabled: false
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: false
```
