### ISSUE TITLE
Resources are not configurable

### ISSUE THREAD

**Issue by mueroema** [openshift/cluster-kube-descheduler-operator#293]
Openshift-Descheduler Resources are preconfigured:

```
containers:
        - resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
```

For large clusters it will direct to OOM Pod restarts. It would be fine to have possiblity to setup in minimum own limits with the KubeDescheduler custom resource.
